### ISSUE TITLE
Test ProBro with older OpenEdge versions

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/ProBro#102]

**Comment by dominickdm** [comment]
Hi Paulius,
Should this extension also work with OE 12.2? I get the error below when I'm connecting to a V12.2 database. It works fine with a 11.7 db.
![image](https://user-images.githubusercontent.com/40289256/187970719-b90c8e85-280a-475e-88fc-1b98950f16df.png)

**Comment by PauliusKu** [comment]
Hi @dominickdm,
Thanks for the input. Yes, currently there is no way to configure it. Also there are some other parameters which we should make configurable too. I will create a separate issue to address it.

**Comment by PauliusKu** [comment]
Hi @dominickdm,
regarding your question about DLC configuration.
In Version 1.1.0 we added setup guide (link: https://github.com/BalticAmadeus/ProBro/blob/HEAD/resources/markdown/setup.md).
Basically you can edit .sh or .bat scripts where you can change DLC parameter. In future releases we'll make this configuration more user friendly.
