### ISSUE TITLE
2 refresh buttons on database explorer

### ISSUE THREAD

**Issue by SharperPS** [BalticAmadeus/ProBro#116]
One button looks like is always disabled

![image](https://user-images.githubusercontent.com/10099488/186369809-c96e7637-0a89-4e4e-b85e-f3d02d5bffb4.png)

**Comment by PauliusKu** [comment]
Strange. First time I see this, but we'll investigate. Thanks

**Comment by PauliusKu** [comment]
Didn't manage to reproduce this bug.
