### ISSUE TITLE
2 Vs code workspaces don't work at the same time

### ISSUE THREAD

**Issue by SharperPS** [BalticAmadeus/ProBro#118]
You can see databases but tables will load just to one workspace

![image](https://user-images.githubusercontent.com/10099488/186371233-f5bd6ff0-ad2d-4603-af4e-920023d0305d.png)

**Comment by PauliusKu** [comment]
At the moment socket server launches on one predefined port, so we cannot use multiple instances for the extension.
It is a valid issue, but we need to find the best solution for it.

**Comment by PauliusKu** [comment]
@Knijus tested your changes. Got 1249 error https://community.progress.com/s/article/000045323. It seems that pf becomes too long.
