### ISSUE TITLE
Table named config does not load

### ISSUE THREAD

**Issue by SharperPS** [BalticAmadeus/ProBro#119]
I have table in database named config. And data for it does not load.
For other tables everything loads if they have data or not. Config table is stuck. (loading more rows)
![image](https://user-images.githubusercontent.com/10099488/186373438-231c4940-9e52-43ef-888f-338dfbfd6b43.png)

**Comment by Knijus** [comment]
Can You provide us with more details? I tried creating config table and everything works fine. I think, this problem may occur due to fields. It would be helpful, if You could provide us with view of fields explorer with data formats.

**Comment by SharperPS** [comment]
@Knijus  attached zip file with .df

[config.zip](https://github.com/BalticAmadeus/ProBro/files/9565699/config.zip)
