### ISSUE TITLE
Sorting data based on the field takes a long time,

### ISSUE THREAD

**Issue by SharperPS** [BalticAmadeus/ProBro#121]
Sorting data based on the field takes a long time,
And while waiting for this sort to finish checking other tables query will get stuck and never finish (you need to reopen queries).
Maybe the issue is that you can send just one query at a time.

![image](https://user-images.githubusercontent.com/10099488/186378381-0c0e182b-e71a-46ec-a61d-1f3caf493d1c.png)

![image](https://user-images.githubusercontent.com/10099488/186378727-5d172a1b-6543-4ef1-b0d9-9f416474b7ad.png)

**Comment by PauliusKu** [comment]
I think this issue was solved. @SharperPS please inform me if you get any other issues with the performance.
