### ISSUE TITLE
Outline and syntax highlights only

### ISSUE THREAD

**Issue by jonathanstarke** [BalticAmadeus/ProBro#158]
Would it be possible to JUST use the Syntax Highlighting, and the Outline display, without having to configure connectivity to the Database etc.

Thnx
Jonathan

**Comment by PauliusKu** [comment]
Hi @jonathanstarke ,

could you elaborate more? I'm not sure we have syntax highlighting in our plugin :)

Paulius

**Comment by PauliusKu** [comment]
Ok, np.

**Comment by PauliusKu** [comment]
Not an issue.
