### ISSUE TITLE
config / setup

### ISSUE THREAD

**Issue by jmls** [BalticAmadeus/ProBro#162]
Wanting to try this extension out - but (embarrassingly) I can't find any way to configure or get the extension to load

There is no `pro-bro` commands in the palette . However, the extension says that it is enabled

![image](https://user-images.githubusercontent.com/929523/198268300-01366868-1f8a-4642-ba6c-359f17b5fa4c.png)
![Screenshot from 2022-10-27 12-05-33](https://user-images.githubusercontent.com/929523/198268593-71099f4e-0603-430f-aa7c-6f5d77e15f07.png)

**Comment by PauliusKu** [comment]
Hi, sorry to hear that.
Can you see the Icon in the left Activity Bar (1)? After selecting it you should be able to se "Plus" button (2) which opens the connection setup window.
![image](https://user-images.githubusercontent.com/36190136/200300557-a8947368-07d8-4f48-986e-c530128b9340.png)

**Comment by PauliusKu** [comment]
@jmls we had an issue with opening setup window on 1.73 VSCode version. We fixed it with 1.0.1 patch. Please, let me know if you get any other issues.

**Comment by jmls** [comment]
I'm afraid that I'm getting the same issue. Unless I'm doing something very wrong :)
 
![Screenshot 2022-11-28 1 41 26 PM](https://user-images.githubusercontent.com/929523/204281374-c43497d4-8ff2-4d00-a786-c90115b788d2.png)

 
![image](https://user-images.githubusercontent.com/929523/204281249-37ac80d9-0091-4b54-826d-b81cf70c78ae.png)

**Comment by PauliusKu** [comment]
@jmls But can you see this ProBro icon (1) on the activity bar? You should be able to use the plugin without commands. I see that we didn't implement correct names for commands, so it is hard to use them. I will fix this issue in an upcoming release.
> Hi, sorry to hear that. Can you see the Icon in the left Activity Bar (1)? After selecting it you should be able to se "Plus" button (2) which opens the connection setup window. ![image](https://user-images.githubusercontent.com/36190136/200300557-a8947368-07d8-4f48-986e-c530128b9340.png)

**Comment by jmls** [comment]
I can see (1) but when pressing (2) I get 
![image](https://user-images.githubusercontent.com/929523/204294319-60cf496a-391b-4da7-996e-6e55c47abb18.png)

**Comment by PauliusKu** [comment]
@jmls Ok, I see. Tts hard to say what could cause it. Could you send me more details:
- OS,
- VSCode version,
- Developer tools console output (ctrl-shift-I)

**Comment by PauliusKu** [comment]
Hi @jmls, I managed to reproduce you issue on Ubuntu. Apparently there were some issue with packaging the extension. We released the fix with version 1.1.0. Also, you can consult setup guide: https://github.com/BalticAmadeus/ProBro/blob/develop/resources/markdown/setup.md

**Comment by PauliusKu** [comment]
Closing this ticket as we plan to go deep in configuration issues for Q3 release. The main idea is to aim for simple and configuration free access while using gitpod or codespaces, having multiple different version DBs or multiple socket servers on remote machines.
