### ISSUE TITLE
Exporting big amounts of data takes much longer than in DataDigger

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/ProBro#203]
Required changes:

1. Improve time performance , so it would be comparable to DataDigger.
2. Show status info during export, so that the user could understand what is happening.

**Comment by Knijus** [comment]
![image](https://user-images.githubusercontent.com/89484925/214826224-86e39a36-fead-485e-a2c2-81ed95bcd684.png)

time is shown in seconds. Biggest difference in time emerges in ProBro OE part. Also, the more records there are, the more time it takes to send data from OE part to middleware.

**Comment by PauliusKu** [comment]
Created new issues:
https://github.com/BalticAmadeus/ProBro/issues/219
https://github.com/BalticAmadeus/ProBro/issues/218
