### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/ProBro#216]
At the moment, logging is all over the place. We should come up with some standard approach and implement it.

Approach:
1. Socket Server logging. Configure log levels, groups, output file etc.
2. Node logging. Add console log on all interactions with React and Socket Server.
3. React logging. Add logging on all interactions with node.

All 3 logging setups should be separatelly adjustable via extension settings.

**Comment by Knijus** [comment]
done
