### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/ProBro#261]
Create welcome page when starting Extension for the first time or when new version is installed

**Comment by MatasVGTU** [comment]
Not everything is finished. I haven't found a solution when loading .md files to load images or other path references. There must be some solution behind webpack configuration. Once this is resolved everything should work as expected. Also when issue is resolved in extension.ts there is a comment (reminder) to change versionChecker.forDebug() to .isNewVersion().

**Comment by MatasVGTU** [comment]
@PauliusKu
