### ISSUE TITLE
Text overlaps due to sorting

### ISSUE THREAD

**Issue by MatasVGTU** [BalticAmadeus/ProBro#289]
Steps to reproduce this bug:
1.Open Table OrderLine
2.Filter OrderLineStatus = Shipped
3.Query "ItemNum < 10"
4.Click Query button
5.Scroll untill all reocords are retrieved (531)
6.Now sort table by different collumns (fast?)
7.Scroll 
8.Repeat 6-7 untill Record counter shows more records than 531
9. Sort some field once and scroll
10. It show that there are (531) records but it overlaps

![image](https://user-images.githubusercontent.com/113093380/225572695-4c6a6dfa-c10c-49c9-af5d-482015cdf078.png)
![image](https://user-images.githubusercontent.com/113093380/225572703-c7350166-e901-4457-ba99-37e1bb61a295.png)

**Comment by mmarkauskas** [comment]
Unable to replicate this bug.
