### ISSUE TITLE
No port provided. Unable to start connection error 

### ISSUE THREAD

**Issue by cverbiest** [BalticAmadeus/ProBro#329]
I installed ProBro in vscode
Changed C:\Users\xxx\.vscode\extensions\balticamadeus.pro-bro-1.3.0\resources\oe\scripts\oe.bat

Added a database
<img width="408" alt="image" src="https://github.com/BalticAmadeus/ProBro/assets/1312691/356fde48-9507-4f62-a292-d52bdf9e4137">

<img width="277" alt="image" src="https://github.com/BalticAmadeus/ProBro/assets/1312691/b1c906da-c3ae-4fd4-9144-590dc2666011">

Test connection shows
<img width="282" alt="image" src="https://github.com/BalticAmadeus/ProBro/assets/1312691/de19f425-4fac-4407-a07b-b53689657a78">

**Comment by cverbiest** [comment]
I got past this error by selecting 
<img width="289" alt="image" src="https://github.com/BalticAmadeus/ProBro/assets/1312691/1ea58855-33d8-4a69-a2fd-eef25acdc45c">
getting a bit further, but it seems I need to restart Vscode before some changes have effect.
I need to select the port each time I start vscode

**Comment by cverbiest** [comment]
Fixed by explicitely specifying ports in the settings

<img width="439" alt="image" src="https://github.com/BalticAmadeus/ProBro/assets/1312691/7f69de02-4be1-4779-9bb4-3c9d9cb92893">

I regulary have multiple vscode windows open so I added a range of ports instead of just one

**Comment by PauliusKu** [comment]
@cverbiest glad you found the solution.
