### ISSUE TITLE
Enhancement request: integrate with Riverside by reusing configuration

### ISSUE THREAD

**Issue by cverbiest** [BalticAmadeus/ProBro#331]
I would be nice if ProBro could detect and use vscode-abl global and project configuration

https://github.com/vscode-abl/vscode-abl

OpenEdge installations can be found in the global config eliminating the need to update oe.bat.
Database connections can be found in the workspace config

**Comment by PauliusKu** [comment]
Hi Carl, that's a nice feature. We already have a similar ticket, but I will keep this one open to have you informed when it's done.

https://github.com/BalticAmadeus/ProBro/issues/321

**Comment by PauliusKu** [comment]
Hi @cverbiest, I am closing this request as it's already implemented with version 1.4.0 and up.
