### ISSUE TITLE
October release plan

### ISSUE THREAD

**Issue by Einingis** [BalticAmadeus/ProBro#440]
- [x] #404
- [x] #438 
- [x] #416
- [x] #399
- [x] #407 
- [x] #381 
- [x] #422 
- [x] #401 
- [x] #400 
- [x] #418 
- [x] #398 
- [x] #395 
- [x] #406 
- [x] #248

**Comment by PauliusKu** [comment]
Test plan:
- [ ] #404 @PauliusKu 
- [ ] #438 @mmarkauskas 
- [ ] #416
- [ ] #399 @Einingis 
- [ ] #407 
- [ ] #381 @PauliusKu 
- [ ] #422 
- [ ] #401
- [ ] #400 @mmarkauskas  
- [ ] #418 @PauliusKu 
- [ ] #398 @PauliusKu 
- [ ] #395 @mmarkauskas 
- [ ] #406 @PauliusKu 
- [ ] #248
