### ISSUE TITLE
December release plan 

### ISSUE THREAD

**Issue by Einingis** [BalticAmadeus/ProBro#491]
- [ ] #457 
- [ ] #470 
- [ ] #463 
- [ ] #445 
- [ ] #479 
- [ ] #473

**Comment by PauliusKu** [comment]
Testing:
- [ ] #457 @PauliusKu 
- [ ] #470 @mmarkauskas 
- [ ] #463 @Einingis 
- [ ] #445 @Einingis 
- [ ] #479 @Einingis 
- [ ] #473 @Einingis
