### ISSUE TITLE
Fix issue with column width formatting

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/ProBro#493]
There are some issues with the function which calculates the width of query grid table columns. The code should be reviewed and fixed.

**Comment by abelzis** [comment]
Bug reproducability:

![image](https://github.com/BalticAmadeus/ProBro/assets/44312404/00d57331-4498-4cf8-bf7f-ef0388718dad)
```
ADD FIELD "Type" OF "ImportInfo" AS CHAR
  FORMAT "X(16)"
  INITIAL ""
  POSITION 3
  ORDER 30
```
