### ISSUE TITLE
January release plan

### ISSUE THREAD

**Issue by PauliusKu** [BalticAmadeus/ProBro#527]
Issue list:

- [ ] https://github.com/BalticAmadeus/ProBro/issues/510
- [ ] https://github.com/BalticAmadeus/ProBro/issues/506
- [ ] https://github.com/BalticAmadeus/ProBro/issues/505
- [ ] https://github.com/BalticAmadeus/ProBro/issues/504
- [ ] https://github.com/BalticAmadeus/ProBro/issues/493
- [ ] https://github.com/BalticAmadeus/ProBro/issues/490
- [ ] https://github.com/BalticAmadeus/ProBro/issues/480
- [ ] https://github.com/BalticAmadeus/ProBro/issues/468
- [ ] https://github.com/BalticAmadeus/ProBro/issues/464
- [ ] https://github.com/BalticAmadeus/ProBro/issues/528
- [ ] https://github.com/BalticAmadeus/ProBro/issues/517
- [ ] https://github.com/BalticAmadeus/ProBro/issues/498

**Comment by PauliusKu** [comment]
Testing.

- [ ] https://github.com/BalticAmadeus/ProBro/issues/510 @mmarkauskas 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/506 @abelzis 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/505 @mmarkauskas 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/504 @PauliusKu 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/493 @mmarkauskas 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/490 @PauliusKu 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/480 @abelzis 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/468 @abelzis 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/464 @mmarkauskas 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/380 @PauliusKu 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/528 @abelzis 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/517 @PauliusKu 
- [ ] https://github.com/BalticAmadeus/ProBro/issues/498 @mmarkauskas

**Comment by abelzis** [comment]
#480 does not seem to be present in the release.

![Image](https://github.com/BalticAmadeus/ProBro/assets/44312404/c48cd3dc-3d1c-4629-a0ec-0f78b60cd703)

**Comment by abelzis** [comment]
#480 tested _OK_ with updated release.

**Comment by PauliusKu** [comment]
https://github.com/BalticAmadeus/ProBro/issues/380 is not present
