### ISSUE TITLE
ProBro VsCode not getting tables due to startup.pf settings

### ISSUE THREAD

**Issue by cverbiest** [BalticAmadeus/ProBro#574]
# Issue : Not getting tables for database

## To Reproduce

1. Start with same steps as #573 
2. Click on LISA database
3. Observe spinner on db name
4. See error in Developer tools

## Expected behavior
table info is collected and shown

## Developer tools output

```
[Extension Host] GroupList 
[{…}]
console.ts:137 [Extension Host] useNew: false
console.ts:137 [Extension Host] execShell params :  
{connectionString: '-db /data/domain/develop/db/LISA   -H domain-develop-dbhost -S 4500 -ct 1', command: 'get_tables'}
console.ts:137 [Extension Host] eyJjb25uZWN0aW********************************************************************************************W1hbmQiOiJnZXRfdGFibGVzIn0=
console.ts:137 [Extension Host] getOeClient error :  Cannot read properties of undefined (reading 'write')
```

## Desktop

 - OS: Red Hat Enterprise Linux release 9.4 (Plow)
 - ProBro Version v1.7.0
 - Other (VSC version, etc.)
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by cverbiest** [comment]
additional info, our $DLC contains following startup.pf.
maybe some parameters conflict with what probro expects.

I'll try commenting those out

```
-cpinternal UTF-8
-cpstream UTF-8
-cpcoll Basic
-cpcase Basic
-d dmy
-numsep 46
-numdec 44
-T /tmp
-Mm 10240

```

**Comment by cverbiest** [comment]
After removing -d, -numsec, -numdec, -T & -Mm and restarting I do get a list of tables.
Not sure with of those parameters causes the problem.

I'll try to make .vscode-server/extensions/balticamadeus.pro-bro-1.7.0/resources/oe/scripts/oe.sh more explicit

**Comment by PauliusKu** [comment]
Merged
